"use client";

import {
  Anchor,
  Beer,
  Bed,
  Bike,
  BookOpen,
  Building,
  Cake,
  Camera,
  Car,
  Church,
  Coffee,
  Compass,
  Dog,
  Dumbbell,
  FerrisWheel,
  Film,
  Flag,
  Flame,
  Flower,
  Gamepad2,
  Gift,
  Heart,
  Hospital,
  Hotel,
  IceCream,
  Landmark,
  Library,
  MapPin,
  Mountain,
  MountainSnow,
  Music,
  Palette,
  Palmtree,
  Pizza,
  Plane,
  School,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Soup,
  Star,
  Store,
  Sun,
  TentTree,
  Train,
  TreePine,
  Utensils,
  Waves,
  Wine,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { type ListIconKey, iconKey } from "./place-list-icons";

// Client-only React-component lookup. Keys must match place-list-icons.ts.
export const PLACE_LIST_ICON_COMPONENTS: Record<ListIconKey, LucideIcon> = {
  compass: Compass,
  "map-pin": MapPin,
  landmark: Landmark,
  "tent-tree": TentTree,
  "tree-pine": TreePine,
  mountain: Mountain,
  "mountain-snow": MountainSnow,
  waves: Waves,
  palmtree: Palmtree,
  flower: Flower,
  sun: Sun,
  utensils: Utensils,
  cake: Cake,
  coffee: Coffee,
  wine: Wine,
  beer: Beer,
  pizza: Pizza,
  "ice-cream": IceCream,
  soup: Soup,
  camera: Camera,
  music: Music,
  film: Film,
  gamepad: Gamepad2,
  palette: Palette,
  "book-open": BookOpen,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  store: Store,
  gift: Gift,
  bed: Bed,
  hotel: Hotel,
  building: Building,
  church: Church,
  library: Library,
  school: School,
  hospital: Hospital,
  dumbbell: Dumbbell,
  heart: Heart,
  anchor: Anchor,
  ship: Ship,
  plane: Plane,
  car: Car,
  bike: Bike,
  train: Train,
  "ferris-wheel": FerrisWheel,
  flame: Flame,
  sparkles: Sparkles,
  star: Star,
  flag: Flag,
  dog: Dog,
};

export function iconFor(k: string | null | undefined): LucideIcon {
  return PLACE_LIST_ICON_COMPONENTS[iconKey(k)];
}
